### ISSUE TITLE
`clone_slice(range: Range) -> Rope`?

### ISSUE THREAD

**Issue by dpc** [cessen/ropey#20]
For implementing copy-paste, it is useful to take part of the `Rope`, as a new `Rope`. Right now I will just have to `clone()` and remove prefix and suffix, which is not too bad, but not ideal. :)

**Comment by cessen** [comment]
`Rope` implements `From<RopeSlice>`, so you can just do `my_rope.slice(a..b).into()`.

More generally, both `Rope` and `RopeSlice` have many useful standard library trait implementations that let you accomplish things like this efficiently, so pay attention to the `impl`s. :-)

Hope this helps!

**Comment by dpc** [comment]
That helps a lot! Thank you!
