### ISSUE TITLE
Make Lines iterator more efficient

### ISSUE THREAD

**Issue by cessen** [cessen/ropey#25]
Currently the `Lines` iterator is roughly equivalent to just calling `Rope::line()` repeatedly with an incrementing index.  This is O(log N) for each call to `Lines::next()`, and also is just generally less efficient than it needs to be.  This is not only sub-optimal, but also stands out compared to the other iterators which are all O(1) and very fast.

It should be possible to also make `Lines` O(1) and just generally more efficient.

**Comment by cvfosammmm** [comment]
Do you keep track of line breaks in a separate data structure? I will assume that you do.

On Wikipedia it says "Report" takes O(j + log n) with j the length of the slice. That's what it costs to get the first line. To get the next line after that you might keep the adress of the last line ending around and get the next k characters by traversing the tree, with k the length of the line. That would cost O(k) if I understand everything correctly.

**Comment by poliorcetics** [comment]
I was exploring this issue this weekend and I think I have a possible solution, I'll try to post a PR within the month :), its needs lots of polishing and perf testing (thankfully testing for correctness is just comparing to the slow version so that part is easy)

**Comment by pascalkuthe** [comment]
> I was exploring this issue this weekend and I think I have a possible solution, I'll try to post a PR within the month :), it needs lots of polishing and perf testing (thankfully testing for correctness is just comparing to the slow version so that part is easy)

That's a bit unfortunate timing we did some duplicate work here (see my comment in helix-editor/helix#4457). Perhaphs we can combinme efforts
