### ISSUE TITLE
Reversible Iterators

### ISSUE THREAD

**Issue by cessen** [cessen/ropey#31]
Ropey's iterators are now bidirectional (see issue #18).  However, there are still use-cases where it is useful or necessary to _reverse_ the iterator so that `next()` moves it backwards instead of forwards.  In particular, right now you can't use any of Rust's iterator methods when iterating backwards.

One possibility would be to implement the `DoubleEndedIterator` trait, which behaves like two independent iterators, one on each end, both moving in opposite directions.  By calling `rev()` you can swap the ends.  However, it's not entirely clear what it would mean, then, to create an iterator starting e.g. in the middle of the rope.

Another possibility is to add a method that simply reverses the direction of the iterator in-place.  This would side-step any awkwardness with `DoubleEndedIterator` and I believe would satisfy the large majority of use-cases.  Moreover, it would make it obvious how to create a reversed iterator starting in the middle of a Rope.  However, it would move Ropey even further away from the way people may initially expect things to work based on iterators in the standard library.

**Comment by archseer** [comment]
I found this a bit awkward when trying to build a reverse iterator that starts at the end of the file. It wasn't immediately obvious that is should be:

```rust
let (mut chunks, _, _, _) = text.chunks_at_byte(text.len_bytes());
``` 

The code then also needs to use `while let Some() = ` over `for`. I do find the additional return values of `chunks_at` very convenient though.

(Sidenote: I got ropey working with regex-automata: https://github.com/helix-editor/helix/blob/8126bcf9765e7e1da7b2223a10232a119d8c334a/helix-core/src/search.rs#L128-L194)

**Comment by cessen** [comment]
Hi @archseer!  Thanks for the poke on this issue.

> I found this a bit awkward when trying to build a reverse iterator that starts at the end of the file. It wasn't immediately obvious that is should be:

Yeah, I can definitely see how that isn't obvious at first glance.  Do you think some better documentation would be enough for this at the moment?  (See below for my current thoughts on `DoubleEndedIterator` and Ropey.)

Another possibility would be to add dedicated convenience-methods for creating iterators at the end of the text, but I'm not sure if that would really pull its own weight in terms of API expansion.

> The code then also needs to use `while let Some() =` over `for`.

Yeah, that's definitely awkward!  And that's largely why I opened this issue.

> (Sidenote: I got ropey working with regex-automata: https://github.com/helix-editor/helix/blob/8126bcf9765e7e1da7b2223a10232a119d8c334a/helix-core/src/search.rs#L128-L194)

That's awesome!  Using Ropey with things like DFA-based regex (such as regex-automata) is one of the primary use-cases I had in mind for this issue.

In particular, DFA regex can only find the end--not the the start--of a match in a single pass (at least, IIRC that's what @burntsushi told me).  To find the start of the match it has to flip directions in-place after finding the end, and run the search again in reverse.  You can do that in Ropey right now with the `prev()` method, but as you mention that's awkward since you can't use it in a for loop.

### Thoughts on `DoubleEndedIterator`

When I initially filed this issue, I felt like functions for reversing Ropey's iterators in-place and implementing `DoubleEndedIterator` were a bit in conflict with each other.  But I'm pretty sure that was just a brain fart.  I think we can implement both without conflict.

Having said that, in-place reversal has known concrete use-cases like DFA regex, whereas I struggle to think of any use-cases for `DoubleEndedIterator` in Ropey aside from being a shortcut for getting iterators at the end of the text.  That in itself wouldn't be a problem, though--normally I'd be happy to implement it as a shortcut.

However, Ropey's iterators aren't lightweight: they have to maintain state for efficient linear-time tree traversal, which both takes time to initially construct and also takes up memory.  Implementing `DoubleEndedIterator` would double that overhead for all of Ropey's iterators.  Essentially, we'd be building and storing two iterators *every time* even when the client code only needs one of the two ends.  And that gives me a bit of pause.

Now, having said *that*, just because *I* can't think of other use-cases for `DoubleEndedIterator` in Ropey doesn't mean they don't exist.  But I would like *someone* to have a concrete use-case for `DoubleEndedIterator` that actually utilizes both ends before committing to that overhead.

So I think what I'm going to do is update this issue to *just* be about in-place reversal, which addresses the `while let Some() = ` issue, and open a new issue calling for concrete use-cases of `DoubleEndedIterator` so we can figure out what people might need it for.

Does that sound reasonable?

**Comment by cessen** [comment]
Immediately after I posted the above, I realized there's another approach we could take for implementing `DoubleEndedIterator`: instead of building and storing two iterators internally, we can just store one iterator and one index.  The index represents the other end's position, and when `rev()` is called we essentially construct an iterator at that index and swap.  This pushes the computational overhead of `DoubleEndedIterator` to when it's actually used (the `rev()` call), and keeps the memory overhead small.

The down side is that we would then be paying the computational overhead of constructing a new iterator *every* time `rev()` is called.  But I think that's a reasonable trade-off, given that (probably?) the most common use-case is as a shortcut to the end of the text, rather than something that's called frequently during traversal.  Or, in other words, the cost of building a `DoubleEndedIterator` was going to be constructing two iterators internally anyway.  So constructing one, and then constructing another when `rev()` is called isn't any worse.

I'd still like to get feedback on possible use-cases first, to see if this would be a problem for the cases where both ends might actually be used.  But this would make it pretty much a non-issue to implement as a shortcut for end-of-text iterators.

**Comment by BurntSushi** [comment]
> In particular, DFA regex can only find the end--not the the start--of a match in a single pass (at least, IIRC that's what @BurntSushi told me). To find the start of the match it has to flip directions in-place after finding the end, and run the search again in reverse.

Yes, that's correct.

**Comment by archseer** [comment]
Something I learned from @PabloMansanet's PR: it's possible to easily wrap the current implementation's `.prev()` method to work with `for` loops:

```rust
let mut slice = slice.chars_at(pos + 1);
let mut chars = std::iter::from_fn(|| slice.prev())

for ch in chars { ... }
```

**Comment by cessen** [comment]
Whoa, that's super cool.  I didn't know about `iter::from_fn()`!  Still want to make these reversible, but that's good to know.

**Comment by cessen** [comment]
Implemented in-place reversal (not `DoubleEndedIterator` yet) in 67fc3fd51327959c9fe0379a59126de150f89dd0.

**Comment by cessen** [comment]
I'm closing this issue as complete, since the original primary use-case I had in mind is now addressed.  But if someone specifically wants `DoubleEndedIterator` as well (and ideally has a use-case) feel free to open another issue.
