### ISSUE TITLE
Implement Range on lines

### ISSUE THREAD

**Issue by dumrich** [cessen/ropey#46]
This may already be a thing, but how could you get only certain lines (e.g. 15-65). Currently I have a loop and use .line(idx), which seems inefficient. Is there any way to do something like this: .lines()[14..65]?

**Comment by cessen** [comment]
You can take a slice of the rope with `slice()`, and then iterate over the lines in the slice.  `slice()` takes a char index range, so you'll need to compute the start and end char indices of the range you want first.

For example, if you want to iterate over the second, third, and fourth lines, you would do this:

```rust
let start = my_rope.line_to_char(1);
let end = my_rope.line_to_char(4);
for line in my_rope.slice(start..end).lines() {
    // Do stuff with the line.
}
```

Hope that helps!
