### ISSUE TITLE
Add slice_byte() / get_slice_byte()

### ISSUE THREAD

**Issue by archseer** [cessen/ropey#49]
It would be a nice optimization in Helix since we receive byte ranges from tree-sitter then convert them into char indices, but then ropey converts back to bytes and uses byte calculations internally.

**Comment by cessen** [comment]
Thanks for the linked PR!

There are some additional things I want to address, as I mentioned in the PR.  So I'm leaving this open as a reminder to take care of that.

**Comment by cessen** [comment]
I've now addressed the additional items I mentioned in the original PR.
