### ISSUE TITLE
Add a feature flag to only count LF and CRLF as line breaks.

### ISSUE THREAD

**Issue by cessen** [cessen/ropey#53]
Most other software does not conform to the [Unicode spec](https://www.unicode.org/reports/tr14/#BK) when it comes to line breaks.  This (understandably) gives people pause when deciding whether to use Ropey or not, because although Ropey is "correct" in the way it counts line breaks, it's not compatible with other software if any line breaks other than LF/CRLF are present in a file.

We can solve this with a feature flag that implements the simpler, non-Unicode-conformant line break counting that is common to most other software.

**Comment by archseer** [comment]
Also related to #43

**Comment by cessen** [comment]
Oh!  Right.  I feel silly now.  Basically a duplicate.

**Comment by cessen** [comment]
Added in 38531e083f8cf5c5b1aeb328361895fb5a9b867c.

There are two new feature flags:
- `cr_lines`, which enables carriage return line break handling.
- `unicode_lines`, which enables full Unicode line break handling.

Both features are enabled by default for backwards compatibility, but can be disabled to strip things down.  Note that `unicode_lines` implies `cr_lines`, since the former is a superset of the latter.

**Comment by cessen** [comment]
On second thought: re-opening, just to remind myself to add proper documentation for this before the next release.

**Comment by cessen** [comment]
Documentation done.
