### ISSUE TITLE
Improve performance of index_convert

### ISSUE THREAD

**Issue by josephg** [cessen/ropey#54]
Hey! I'm using the str_utils code in another project and I was reading the sse code to understand it better.

In ByteChunk for sse2::__m128i the code currently does this:

```rust
    #[inline(always)]
    fn sum_bytes(&self) -> usize {
        const ONES: u64 = std::u64::MAX / 0xFF;
        let tmp = unsafe { std::mem::transmute::<Self, (u64, u64)>(*self) };
        let a = tmp.0.wrapping_mul(ONES) >> (7 * 8);
        let b = tmp.1.wrapping_mul(ONES) >> (7 * 8);
        (a + b) as usize
    }
```

.. Which is a neat trick, but it makes the "vertical" loop have to build the accumulator every 31 iterations so you don't overflow. I'm no expert at this stuff, but [some reading](https://stackoverflow.com/questions/6996764/fastest-way-to-do-horizontal-sse-vector-sum-or-other-reduction) recommended using [`PSADBW(x, 0)`](https://www.felixcloutier.com/x86/psadbw) ("Compute sum of absolute differences") instead to accumulate into the array.

So changing the code to this:

```rust
    #[inline(always)]
    fn max_acc() -> usize {
        255
    }

    #[inline(always)]
    fn sum_bytes(&self) -> usize {
        unsafe {
            let zero = sse2::_mm_setzero_si128();
            let diff = sse2::_mm_sad_epu8(*self, zero);
            let (low, high) = std::mem::transmute::<Self, (u64, u64)>(diff);
            (low + high) as usize
        }
    }
```

This yields a (modest) performance improvement on my ryzen 5800:

```
ropey:master $ taskset 0x1 nice -10 RUSTFLAGS=-C target-cpu=native cargo criterion -- --measurement-time=10 index_convert
   Compiling ropey v1.3.2 (/home/seph/3rdparty/ropey)
    Finished bench [optimized] target(s) in 37.01s
index_convert/byte_to_char                                                                             
                        time:   [41.762 ns 41.799 ns 41.837 ns]
                        change: [-1.0722% -0.8577% -0.6697%] (p = 0.00 < 0.05)
                        Change within noise threshold.
index_convert/byte_to_line                                                                            
                        time:   [103.24 ns 103.25 ns 103.27 ns]
                        change: [+1.1863% +1.2842% +1.3631%] (p = 0.00 < 0.05)
                        Performance has regressed.
index_convert/char_to_byte                                                                             
                        time:   [87.674 ns 87.701 ns 87.730 ns]
                        change: [-1.6249% -1.5190% -1.4211%] (p = 0.00 < 0.05)
                        Performance has improved.
index_convert/char_to_line                                                                            
                        time:   [153.53 ns 153.55 ns 153.57 ns]
                        change: [-1.4996% -1.3924% -1.2970%] (p = 0.00 < 0.05)
                        Performance has improved.
index_convert/line_to_byte                                                                            
                        time:   [143.57 ns 143.65 ns 143.77 ns]
                        change: [-7.6773% -7.5422% -7.3956%] (p = 0.00 < 0.05)
                        Performance has improved.
index_convert/line_to_char                                                                            
                        time:   [143.31 ns 143.34 ns 143.39 ns]
                        change: [-7.9232% -7.8228% -7.7185%] (p = 0.00 < 0.05)
                        Performance has improved.
```

Is this code change correct?

**Comment by archseer** [comment]
Unrelated but have you seen https://github.com/josephg/jumprope-rs/issues/1 (splitting str_utils into a new crate)?

**Comment by cessen** [comment]
Ah!  Thanks for the tip!  I'm certainly no expert in SIMD optimization either, but the change looks correct to me.

If you want to submit a PR for it, I'll happily merge it.  Otherwise I'll make the change myself when I get around to it.

(Also, I second @archseer's poke to please look at the linked issue on jumprope. :-) )

**Comment by josephg** [comment]
Hmmm, I've just been playing around - and I'm gonna put some notes here for reference later.

- For reference, there's a C++ library called [simdutf](https://github.com/simdutf/simdutf) which implements a lot of these methods, and claims to have excellent performance. Its using some AVX instructions which are still only available in unsafe rust, so we might want to steer clear of them. But its a nice reference. Eg, [here's their code for `count_chars_in_bytes`](https://github.com/simdutf/simdutf/blob/master/src/generic/utf8.h):

```c++
simdutf_really_inline size_t count_code_points(const char* in, size_t size) {
    size_t pos = 0;
    size_t count = 0;
    for(;pos + 64 <= size; pos += 64) {
      simd8x64<int8_t> input(reinterpret_cast<const int8_t *>(in + pos));
      uint64_t utf8_continuation_mask = input.lt(-65 + 1);
      count += 64 - count_ones(utf8_continuation_mask);
    }
    return count + scalar::utf8::count_code_points(in + pos, size - pos);
}
```

I'm confused by a few things - but mostly, why aren't they pulling off the first unaligned section of bytes?

- I've also been goofing around with different implementations of `count_chars_in_bytes` to see what can be done. Tweaking the inner loop seems to make almost no difference to the criterion benchmark result - which is weird! I suspect with this data set / benchmark data we're running into memory bandwidth bottlenecks or something like that. The current code runs the benchmark in 41.3 ns. If I swap the complex simd implementation with this:

```rust
#[inline(always)]
fn count_chars_naive(text: &[u8]) -> usize {
    let mut inv_count = 0;

    for byte in text.iter() {
        inv_count += ((byte & 0xC0) == 0x80) as usize;
    }
    text.len() - inv_count
}
```

Then performance is essentially unchanged, at 42.2ns. But maybe we shouldn't be too surprised at that - it looks like llvm is generating some pretty fancy code itself to try and optimize this. [Here's the code on godbolt](https://godbolt.org/z/zf6TE7Eer).

So if we want to make this code any faster, it might also be worth pulling in some different benchmark data - like, maybe the [stuff simdutf uses](https://github.com/simdutf/simdutf/tree/master/benchmarks/dataset) which is the contents of the "mars" wikipedia page text in a bunch of languages.

Alternately, if llvm is going to go to so much work optimizing this code anyway, I might be able to just use the naive implementation in jumprope and leave vectorization to the compiler.

**Comment by cessen** [comment]
> Its using some AVX instructions which are still only available in unsafe rust

SSE is also unsafe--basically all the SIMD intrinsics are.  I actually implemented an AVX version in `str_utils` as well, but decided to leave it out for basically two reasons:

1. Using AVX instructions causes the CPU clock to throttle on most (all?) processors.  It's worth it if you're really crunching a lot of numbers for a sustained period of time (like e.g. in a 3d renderer, video encoding, etc.) because the increased parallelism beats out the lost clock speed.  But it's less clear if AVX is a win for something like Ropey which is intended to be part of a larger application (text editor), which may want the clock speed for other things.  It still might be a win, but it didn't seem worth it to me to pursue, especially since more significant performance gains can probably be had in other ways anyway.  (And your work on jumprope is good evidence of that, ha ha.)
2. By sticking to SSE2 and lower, Ropey doesn't have to do any fancy conditional CPU feature detection stuff on x86_64 architectures.  I like that simplicity, as well as avoiding the conditional branches.

> I'm confused by a few things - but mostly, why aren't they pulling off the first unaligned section of bytes?

Hmm.  My guess is that they're taking advantage of unaligned reads into the SIMD registers (which I think is a thing?).  We could potentially do that as well, but it would require reading from raw pointers, I think...?  Which would be more unsafe code.  Ideally I'd like to minimize unsafe code unless it really pulls its weight performance-wise.

> So if we want to make this code any faster, it might also be worth pulling in some different benchmark data - like, maybe the [stuff simdutf uses](https://github.com/simdutf/simdutf/tree/master/benchmarks/dataset) which is the contents of the "mars" wikipedia page text in a bunch of languages.

Yeah, after splitting `str_utils` into a separate crate, setting up a bunch more benchmarks is a great idea.  I did something similar in a [PR to the `unicode-segmentation` crate](https://github.com/unicode-rs/unicode-segmentation/pull/78).

**Comment by josephg** [comment]
> Its using some AVX instructions which are still only available in unsafe rust

Sorry; its using some AVX instructions which are only available in *unstable / nightly* rust.

And yeah I understand. I think the other reason it doesn't necessarily make sense to use 256/512 bit registers is that the strings I'm scanning are almost never that long anyway. In jumprope the sweet spot for performance seems to be around 300-400 characters per leaf node. Given the average leaf will be half that length (200) then split in 2 (100) by the gap buffer, you can see how it wouldn't necessarily get much benefit from scanning 64 characters per iteration of the loop.

Pulling it all out into a separate library sounds great.

If you go down that road, I'm very curious what gap buffers to ropey's leaf nodes would do to performance.

**Comment by cessen** [comment]
> Sorry; its using some AVX instructions which are only available in unstable / nightly rust.

Ah, got it.  I think the 256 instructions are stable, though.  Or at least, a lot of them.  But yeah, the 512 intrinsics are certainly still unstable.

> you can see how it wouldn't necessarily get much benefit from scanning 64 characters per iteration of the loop.

Yeah, agreed.  This is one of those situations where the "fastest possible implementation" in the general case doesn't necessarily turn out to be the best for a more specific use case.  It's part of the reason I didn't just pull in e.g. the `bytecount` crate for Ropey (that, and it wouldn't have been able to handle all the unicode line endings anyway).

> If you go down that road, I'm very curious what gap buffers to ropey's leaf nodes would do to performance.

Someone made an issue (#45) about that a while ago.  And I was reminded of that when looking at your Rust implementation of jumprope.  Based on the performance you've gotten out of it, I may revisit the idea.  But I do think the current implementation of Ropey has already spent its complexity budget (so to speak).  So exploring that will probably need to wait until a hypothetical Ropey 2.0 in the future.

**Comment by cessen** [comment]
`str_utils` has now been split out into a separate crate:
https://crates.io/crates/str_indices

I only did *very* minimal clean up, so it's still pretty messy as a stand-alone crate.  But should be good enough for now.

**Comment by cessen** [comment]
I've now cleaned up the code and API in the new crate, and added basic documentation.

@josephg @archseer I've also invited both of you as owners of the crate, for better bus factor.

**Comment by josephg** [comment]
Thanks for splitting that code out! Much appreciated :heart:

**Comment by cessen** [comment]
You're welcome!  Incidentally, in your commit message when switching jumprope-rs over you said:

> Swapped from inlined str tools to str_indices. Small perf improvement for some reason

Just to clear up the mystery: it's because in addition to splitting it out, I also ended up doing some additional perf work on it.  So `str_indices` actually is faster than what was in Ropey before.

**Comment by josephg** [comment]
Ah awesome! Its another ~4% or so perf boost. I was worried the opposite would happen, since the compiler has a harder time optimizing across crate boundaries. Nice work :D

**Comment by cessen** [comment]
@josephg 
In jumprope-rs's fast_str_tools.rs source file you're using some simpler alternatives to the `str_indices` functions for some of your functions, with comments saying that they're faster.  Have you checked if that's still the case?

I tested your functions out in the `str_indices` benchmarks, and they were consistently outperformed there (with the exception of a couple cases where the compiler had obviously managed to "optimize" them down to constants).  But that doesn't necessarily translate to usage in a more complex code base, so I'm curious.

**Comment by josephg** [comment]
I'm just running my benchmarks again now and yeah, I'm seeing a few % better performance using the newer version of str_indices::utf16::count_surrogates.

But your str_indices::chars::count() method loses me 2-10% performance across the board compared to the compiler's version. No idea why. The [compiler's version of this method is mega fancy though](https://godbolt.org/z/bWsr6nedv), which probably helps. Or take a look at [count_utf16_surrogates_in_bytes](https://godbolt.org/z/cjen7jheT).

I also don't have a lot of confidence in my benchmarks at the moment because I don't have any real-world example data sets which aren't English. So all my real testing data is full of ascii characters and not much else. And I'm skipping a lot of calls to these methods when you're just using ASCII. Maybe it would be worth adding another test where I replace all the characters in my dataset with japanese characters and see what happens.

Another interesting thing I noticed: The naive versions of those methods were consistently faster in my tests compared to the non-SIMD versions of the same functions you have in str_indices. And by a lot - they were like 2-3x faster. And all else being equal, if we can lean on autovectorization, we should since it should output better wasm code. (Though I haven't (yet) tried to run criterion benchmarks on wasm output.)

I'm curious - try running your benchmarks again with the SIMD versions disabled and see how performance like that compares to my naive implementations of those methods. If you see the same thing I do (which is, naive code outperforming the `<usize>` variants) then it might be worth using naive versions of those methods in str_indices instead when x86 SIMD isn't available.

**Comment by archseer** [comment]
`chars::count`: This recently came up in https://github.com/cessen/str_indices/issues/8, nightly has an optimized implementation now: https://github.com/rust-lang/rust/pull/90414

Based on the results though, the new version of `str_indices` is supposedly faster (on M1 at least)

**Comment by josephg** [comment]
Huh... I'll try rerunning the same experiment on my M1 laptop. I've been testing everything else on a ryzen 5800 and I bet the results are super different. It certainly is with wasm - [llvm will happily vectorize the naive version of chars::count in wasm](https://godbolt.org/z/3Mfxbqfoa).

I think the difference is string length. A lot of my calls to chars::count are when I'm measuring inserted text. The traces I'm using usually insert very short strings (one of my test cases only has single character insertions). I think the naive code is faster in that case. When I buffer / aggregate changes before calling insert(), the str_indices' simd versions are better.

**Comment by josephg** [comment]
... And if its relevant, I compile everything with `RUSTFLAGS="-C target-cpu=native"`

**Comment by cessen** [comment]
Okay, so after some more investigation, it looks like this is indeed the issue:

> The traces I'm using usually insert very short strings (one of my test cases only has single character insertions).

For something like a text editor, single characters are a *super* common case.  So I've now added that to `str_indices`'s benchmarks as well.  Here are the results (with the "jumprope" variant being the simple version you had in jumprope-rs, and the 0001 etc. being the length of the test string in bytes):

```
chars_english_0001/count:           [2.9808 ns 2.9914 ns 3.0008 ns]
chars_english_0001/count_jumprope:  [1.3983 ns 1.4038 ns 1.4091 ns]

chars_english_0010/count:           [7.6672 ns 7.6965 ns 7.7249 ns]
chars_english_0010/count_jumprope:  [7.8138 ns 7.8402 ns 7.8694 ns]

chars_english_0100/count:           [10.280 ns 10.321 ns 10.361 ns]
chars_english_0100/count_jumprope:  [18.417 ns 18.477 ns 18.544 ns]

chars_english_1000/count:           [30.181 ns 30.305 ns 30.433 ns]
chars_english_1000/count_jumprope:  [152.51 ns 152.57 ns 152.62 ns]

chars_japanese_0003/count:          [4.2629 ns 4.2799 ns 4.2968 ns]
chars_japanese_0003/count_jumprope: [3.6291 ns 3.6449 ns 3.6598 ns]

chars_japanese_0100/count:          [11.651 ns 11.699 ns 11.743 ns]
chars_japanese_0100/count_jumprope: [19.827 ns 19.903 ns 19.982 ns]

chars_japanese_1000/count:          [30.775 ns 30.890 ns 30.999 ns]
chars_japanese_1000/count_jumprope: [153.82 ns 154.27 ns 154.79 ns]
```

For single characters (en 0001 and jp 0003) the simpler code path wins out.  But as the strings get longer, the simd variant overtakes it in performance.

I noticed that you're now special-casing single-byte strings in jumprope-rs, so I presume you figured this out as well.  Following your lead, and special-casing single-byte strings, as well as going a bit further and also special-casing strings shorter than simd chunks, the new results are:

```
chars_english_0001/count:           [307.45 ps 308.60 ps 309.79 ps]
chars_english_0010/count:           [6.2815 ns 6.3065 ns 6.3310 ns]
chars_english_0100/count:           [9.8208 ns 9.8456 ns 9.8660 ns]
chars_english_1000/count:           [30.818 ns 30.951 ns 31.138 ns]
chars_japanese_0003/count:          [2.9778 ns 2.9914 ns 3.0055 ns]
chars_japanese_0100/count:          [11.102 ns 11.145 ns 11.185 ns]
chars_japanese_1000/count:          [30.956 ns 31.094 ns 31.224 ns]
```

So that's a pretty obvious win!

I suspect similar optimizations would benefit the other functions as well, so I'll work on that and then push these changes.  I'll post here again when that's done, so you can test.

**Comment by cessen** [comment]
@josephg
I've pushed the aforementioned optimizations to [str_indices](https://github.com/cessen/str_indices) master.  If you wouldn't mind testing your benchmarks with that to see if it narrows or eliminates the performance gap with your current in-tree implementation, that would be great.  Thanks!

**Comment by josephg** [comment]
Awesome - will do! Yeah adding that simple case for 0 & 1 byte strings and then using the simd version for 2+ bytes improved benchmark performance across the board. Well, at least on my M1. I need an easier way to test across both my computers.

I’ll have a play with the new str_indices code on Monday. Thanks for the tweak!

**Comment by cessen** [comment]
Great!  Looking forward to hearing back.

Also, thanks for helping out with this, and for the idea of specializing for short strings.

**Comment by josephg** [comment]
I don't know how much performance here really matters in practice, but I find it super fun making performance numbers go up. Its fun to have someone else to bounce these ideas off :D

**Comment by josephg** [comment]
So my old code was this:

```rust
// str_indices = "0.3.1"

#[inline]
pub(crate) fn count_chars_in_bytes(text: &[u8]) -> usize {
    if text.len() <= 1 { text.len() }
    else { unsafe { str_indices::chars::count(std::str::from_utf8_unchecked(text)) } }
}
```

New code:

```rust
// str_indices = { git = "https://github.com/cessen/str_indices" }

#[inline]
pub(crate) fn count_chars_in_bytes(text: &[u8]) -> usize {
    unsafe { str_indices::chars::count(std::str::from_utf8_unchecked(text)) }
}
```

And performance went down by ~5% in the normal tests:

![image](https://user-images.githubusercontent.com/47413/159150930-ffaa1442-47dd-4384-8b77-bb71c14ede7d.png)

... And it looks like I get that performance regression just moving from 0.3.1 to master regardless of my code.

If you want, you can run my benchmarks yourself. Just check out jumprope and run:

```
RUSTFLAGS='-C target-cpu=native' cargo criterion --no-run && sleep 10 && RUSTFLAGS='-C target-cpu=native' taskset 0x1 nice -10 cargo criterion  -- --measurement-time=10 
```

(Take out the `tasksel` call on macos)
