### ISSUE TITLE
Is it okay if I publish a fork of this crate that works with any type of data?

### ISSUE THREAD

**Issue by AhoyISki** [cessen/ropey#80]
Essentially, I have taken Ropey and modified it so that, instead of working with text, it would work with an arbitrary data type. Specifically, it would work with an implementor of `Measurable`, a trait that gives elements an arbitrary "width", which can be any number from `0` to `usize::MAX`.

I just wanted to know if it was okay for me to publish this crate on `crates.io` and call it Any-Ropey.

Just to be clear, this crate is not a superset of Ropey. Ropey is still way better at dealing with `string`s, and you pretty much can't use those at all in Any-Ropey. Any-Ropey also doesn't have the concept of `char`s or `line`s, as those don't make sense in an arbitrary data type.

While I don't foresee much use for Any-Ropey out there, I think it might still be useful for someone, so publishing it seem apt. But if you're not okay with it, I won't publish, just use it privately.

If you're interested in checking it out, it can be found [here](https://github.com/AhoyISki/any-ropey), but do keep in mind that the documentation hasn't been changed yet, so the page just looks like Ropey.

**Comment by cessen** [comment]
That sounds useful, yeah!  I don't have any problem with you publishing it, but I think naming it something completely different from Ropey and more descriptive would make more sense.  DataRope?  RopeArray?  Dunno.  But basically, it doesn't really have a meaningful relationship to Ropey anymore, so just making a clean break with the naming is better, I think.

(I imagine you already intend to do this, but from a brief look at the repo it also looks like the readme and documentation still need to be updated before publishing.  So just a reminder to do that as well.  A crate is a lot less useful without up-to-date documentation. :-) )

**Comment by AhoyISki** [comment]
I was gonna name it AnyRopey mostly because the core, and about 80% of the code, is just Ropey with a few changes. And also, I think it's a good sounding name.

**Comment by cessen** [comment]
My main concern is that people will think the projects are related (e.g. maintained by the same/overlapping group of people).  Naming it something completely different helps make it clear that the projects are developed completely separately.

But I guess I don't feel *too* strongly about it, so it's up to you.  But I do recommend picking a completely new and unrelated name.
