### ISSUE TITLE
Chars::reversed not working as expected

### ISSUE THREAD

**Issue by TornaxO7** [cessen/ropey#93]
Here is the minimal example:
```rust
use ropey::Rope;

fn main() {
    let string = Rope::from_str("Hello there!");

    println!("{:?}", string.chars().collect::<String>());
    println!("{:?}", string.chars().reversed().collect::<String>());
}
```
Output:
```
"Hello there!"
""
```
is that expected because I'd expect to get:
```rust
"Hello there!"
"!ereht olleH"
```

**Comment by pascalkuthe** [comment]
Please read the documentation of the iterator module. Rev and reversed are not the same. Ropey iterators are cursors and not double ended. This is expected behavior.

**Comment by TornaxO7** [comment]
oops. Sorry
